include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Athena LED Control
LUCI_DEPENDS:=+luci-base +athena-led +zoneinfo-core +zoneinfo-asia @TARGET_qualcommax_ipq60xx_DEVICE_jdcloud_re-cs-02
PKG_MAINTAINER:=Sh1roko233 <https://github.com/Sh1roko233>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
